version: '3.9'
services:
  posts:
    image: saifaldin3388/dummy_app:10
    command: node index.js
    volumes:
      - /home/db:/var/lib/sqlite/db
    environment:
      APP_NAME: posts
      POSTS_URL: http://localhost:3000
      NOTIFICATIONS_URL: http://localhost:3001
    network_mode: host
  notifications:
    image: saifaldin3388/dummy_app:10
    command: node index.js
    volumes:
      - /home/db:/var/lib/sqlite/db
    environment:
      APP_NAME: notifications
      PORT: 3001
      POSTS_URL: http://localhost:3000
      NOTIFICATIONS_URL: http://localhost:3001
    network_mode: host

