apiVersion: v1
kind: Pod
metadata:
  name: posts
  labels:
    applocation: posts
spec:
  containers:
    - name: posts
      image: saifaldin3388/dummy_app:05
      command: ['node']
      args: ['index.js']
      env:
        - name: APP_NAME
          value: posts
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: notifications
  labels:
    applocation: notifications
spec:
  containers:
    - name: notifications
      image: saifaldin3388/dummy_app:05
      command: ['node']
      args: ['index.js']
      env:
        - name: APP_NAME
          value: notifications
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
