name: Pickly backend

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [main]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  test:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - run: yarn
      - run: yarn test
