name: Pickly backend

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [main]
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{steps.prepare.outputs.sha}}
      version: ${{steps.prepare.outputs.version}}
      dockerfile: Dockerfile
      image: saifaldin3388/dummy_app
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ::set-output name=sha::$(git rev-parse HEAD)
          echo ::set-output name=version::$(git rev-parse --short=4 HEAD)
  build-and-push:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependancies
        run: yarn

      - name: run tests
        run: yarn test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push to dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{needs.prepare.outputs.image}}:${{needs.prepare.outputs.version}}
