name: Pickly backend

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.prepare.outputs.sha }}
      version: ${{ steps.prepare.outputs.version }}
      image: saifaldin3388/app
      dockerfile: Dockerfile
    steps:
      - uses: actions/checkout@v2
      - id: prepare
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
          echo "::set-output name=version::$(git rev-parse --short=4 HEAD)"
  build-docker_image:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: install-dependencies
        run: yarn

      # - id: run-unit-tests
      #   run: yarn test

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{needs.prepare.outputs.image}}
          dockerfile: ${{needs.prepare.outputs.dockerfile}}
          tags: ${{needs.prepare.outputs.version}}

# name: Pickly backend

# on:
#   pull_request:
#     types: [opened, reopened, synchronize, closed]
#     branches: [main]
# jobs:
#   prepare:
#     runs-on: ubuntu-latest
#     outputs:
#       sha: ${{steps.prepare.outputs.sha}}
#       version: ${{steps.prepare.outputs.version}}
#       dockerfile: Dockerfile
#       image: saifaldin3388/app
#     steps:
#       - uses: actions/checkout@v2
#       - run: |
#           echo ::set-output name=sha::$(git rev-parse HEAD)
#           echo ::set-output name=version::$(git rev-parse --short=4 HEAD)
#   build-and-push:
#     needs: [prepare]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: install dependancies
#         run: yarn

#       - name: run tests
#         run: yarn test
        
#       - name: echo
#         run: |
#           echo ${{needs.prepare.outputs.image}}
#           echo ${{needs.prepare.outputs.version}}
#           echo ${{needs.prepare.outputs.sha}}

#       - name: push to dockerhub
#         uses: docker/build-push-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           repository: ${{needs.prepare.outputs.image}}
#           dockerfile: ${{needs.prepare.outputs.dockerfile}}
#           tags: ${{needs.prepare.outputs.version}}
